project:
  name: celeste 
  regions:
    - us-east-1

tests:
  NVirginia:
    template: templates/master.yaml
    regions:
      - us-east-1
    parameters:
      AvailabilityZones: us-east-1a,us-east-1b,us-east-1c,us-east-1d
      AlignstatsImageRepo: alignstats0.9.1
      BidPercentage: 100
      DesiredvCpus: 0
      DragenInstanceType: f1.4xlarge
      DragenTimeout: 86400
      EnvironmentValue: test
      GenomicsS3Bucket: $[taskcat_autobucket]
      KeyPairName: KeyPair
      MinvCpus: 0
      OperationsDataBucket: op-data-bucket
      PrivateSubnet1CIDR: 10.60.0.0/19
      PrivateSubnet2CIDR: 10.60.33.0/19
      PrivateSubnet3CIDR: 10.60.64.0/19
      PrivateSubnet4CIDR: 10.60.96.0/19
      PublicSubnet1CIDR: 10.60.128.0/20
      PublicSubnet2CIDR: 10.60.145.0/20
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: aws-clinical-dragen-env/
      ReportsInstanceType: m6g.large
      ReportsPlusInstanceType: m6g.xlarge
      IntervarInstanceType: m6g.2xlarge
      RetryNumber: 5
      ScandiumImageRepo: scandium1.4.2/htslib1.10.2
      LiftoverIntersectImageRepo: liftover-intersect
      LiftoverPreprocessingImageRepo: liftover-preprocessing
      LiftoverImageRepo: liftover-liftover
      StargazerImageRepo: stargazer1.0.9
      VerifyBamIDImageRepo: verifybamid1.1.3
      IntervarImageRepo: intervar
      MpileupImageRepo: mpileup
      CassandraImageRepo: cassandra-cassandra
      ConcordanceImageRepo: ngird:fingerprint_1.3.0
      VPCCIDR: 10.60.0.0/16
