AWSTemplateFormatVersion: "2010-09-09"

Description: This CloudFormation template deploys Celeste, an environment to run 
  Illumina's DRAGEN software (dragen stack from AWS Quickstart qs-1oqea6246)
  along with HGSC QC reporting tools in a new VPC. This template provisions
  resources spanning AWS Batch, Lambda, IAM, ECR, SNS, and more, and provides
  a basic framework for the automation of high-throughput genomics
  workflows in the cloud.

  
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
        - AvailabilityZones
        - VPCCIDR
        - PrivateSubnet1CIDR
        - PrivateSubnet2CIDR
        - PrivateSubnet3CIDR
        - PrivateSubnet4CIDR
        - PublicSubnet1CIDR
        - PublicSubnet2CIDR
    - Label:
        default: BATCH Quick Start Configuration
      Parameters:
        - DragenInstanceType
        - ReportsInstanceType
        - ReportsPlusInstanceType
        - IntervarInstanceType
        - KeyPairName
        - BidPercentage
        - MinvCpus
        - DesiredvCpus
        - GenomicsS3Bucket
        - RetryNumber
        - DragenTimeout
        - OperationsDataBucket
        - AlignstatsImageRepo
        - VerifyBamIDImageRepo
        - LiftoverIntersectImageRepo
        - LiftoverPreprocessingImageRepo
        - LiftoverImageRepo
        - StargazerImageRepo
        - IntervarImageRepo
        - MpileupImageRepo
        - CassandraImageRepo
        - ConcordanceImageRepo
    - Label:
        default: AWS Quick Start Configuration
      Parameters:
        - QSS3BucketName
        - QSS3KeyPrefix
    - Label:
        default: AWS Environment Configuration
      Parameters:
        - EnvironmentValue
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      KeyPairName:
        default: Key Pair Name
      PrivateSubnet1CIDR:
        default: Private Subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private Subnet 2 CIDR
      PrivateSubnet3CIDR:
        default: Private Subnet 3 CIDR
      PrivateSubnet4CIDR:
        default: Private Subnet 4 CIDR
      PublicSubnet1CIDR:
        default: Public Subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public Subnet 2 CIDR
      VPCCIDR:
        default: VPC CIDR
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      DragenInstanceType:
        default: Dragen Instance Type
      ReportsInstanceType:
        default: Reports Instance Type
      ReportsPlusInstanceType:
         default: Reports Plus Instance Type
      IntervarInstanceType:
         default: Intervar Instance Type
      BidPercentage:
        default: Spot Bid Percentage
      RetryNumber:
        default: AWS Batch Retry Number
      DragenTimeout:
        default: Dragen Timeout
      MinvCpus:
        default: Min vCPUs
      DesiredvCpus:
        default: Desired vCPUs
      GenomicsS3Bucket:
        default: Genomics Data Bucket
      OperationsDataBucket:
        default: Operations Data Bucket
      WgsBucket:
        default: Wgs Bucket
      EnvironmentValue:
        default: Environment Value
      AlignstatsImageRepo:
        default: Alignstats Image Repo
      VerifyBamIDImageRepo:
        default: VerifyBamID Image Repo
      LiftoverIntersectImageRepo:
        default: Liftover Intersect Image Repo
      LiftoverPreprocessingImageRepo:
        default: Liftover Preprocessing Image Repo
      LiftoverImageRepo:
        default: Liftover Image Repo
      StargazerImageRepo:
        default: Stargazer Image Repo
      IntervarImageRepo:
        default: Intervar Image Repo
      MpileupImageRepo:
        default: Mpileup-cassandra Image Repo
      CassandraImageRepo:
        default: Cassandar Image Repo
      ConcordanceImageRepo:
        default: Concordance Image Repo


Parameters:
  AvailabilityZones:
    Description: The list of Availability Zones to use for the subnets in the VPC.
      The Quick Start uses two Availability Zones from the provided list and 
      preserves the logical order specified.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  DragenInstanceType:
    AllowedValues:
      - f1.2xlarge
      - f1.4xlarge
      - f1.16xlarge
    Description: EC2 instance type for DRAGEN in the AWS Batch Compute Environment.
    Type: String
  ReportsInstanceType:
    AllowedValues:
      - m5.large
      - m5a.large
      - m6g.large
    Description: EC2 instance type for running reports in AWS Batch
    Type: String
  ReportsPlusInstanceType:
    AllowedValues:
      - m5.xlarge
      - m5a.xlarge
      - m6g.xlarge
    Description: EC2 instance type for running more compute intensive reports in AWS Batch (xlarge)
    Type: String
  IntervarInstanceType:
    AllowedValues:
      - m5.large
      - m5a.large
      - m5.xlarge
      - m5a.xlarge
      - m5a.2xlarge
      - m6g.large
      - m6g.xlarge
      - m6g.2xlarge
    Description: EC2 instance type for running InterVar in AWS Batch
    Type: String
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you
      to securely connect to your instance after it launches.
    Type: AWS::EC2::KeyPair::KeyName
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/19
    Description: The CIDR block for the private subnet located in Availability Zone 1.
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.33.0/19
    Description: The CIDR block for the private subnet located in Availability Zone 2.
    Type: String
  PrivateSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.64.0/19
    Description: The CIDR block for the private subnet located in Availability Zone 3.
    Type: String
  PrivateSubnet4CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.96.0/19
    Description: The CIDR block for the private subnet located in Availability Zone 4.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: The CIDR block for the public (DMZ) subnet 1 located in Availability Zone 1.
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.145.0/20
    Description: The CIDR block for the public (DMZ) subnet 2 located in Availability Zone 2.
    Type: String
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: The CIDR block for the VPC.
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with
      a hyphen (-).
    Description: S3 bucket name for the Quick Start assets.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, 
      lowercase letters, uppercase letters, hyphens (-), and a forward slash
      (/) at the end of the prefix.
    Description: S3 key prefix for the Quick Start assets. Use trailing slash (/)
      if object name requires.
    Type: String
  BidPercentage:
    AllowedPattern: (?:\b|-)([1-9]{1,2}[0]?|100)\b
    ConstraintDescription: Spot Bid should be between 1 and 100, inclusive.
    Description: The bid percentage set for the AWS Batch Managed Compute
      Environment with Spot Instances.
    Default: 50
    Type: String
  RetryNumber:
    AllowedPattern: (?:\b|-)([1-9]|10)\b
    ConstraintDescription: Value between 1 and 10
    MaxLength: 1
    Default: "5"
    Description: Number of retries for each AWS Batch job. Integer required.
    Type: String
  DragenTimeout:
    Type: String
    Description: Number of seconds before Dragen Batch job times out.
    AllowedPattern: ^[1-9]\d*$
    ConstraintDescription: Positive integer not beginning with 0
  MinvCpus:
    AllowedPattern: ^(0|[1-9][0-9]{0,2}|1000)$
    ConstraintDescription: Valid between 0 and 1000, inclusive
    Description: Minimum number of vCPUs in the compute environment. Default 0.
    Default: 0
    Type: String
  DesiredvCpus:
    AllowedPattern: ^(0|[1-9][0-9]{0,2}|1000)$
    ConstraintDescription: Valid between 1 and 1000, inclusive
    Description: Desired number of vCPUs. Compute environments will provision
      this number of vCPUs at launch time. Default 0.
    Default: 0
    Type: String
  GenomicsS3Bucket:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: S3 genomics bucket name can include numbers,
      lowercase letters, uppercase letters, and hyphens (-). It cannot
      start or end with a hyphen (-).
    Description: Name of S3 bucket for reading and writing genomics data.
    Type: String
  OperationsDataBucket:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: S3 genomics bucket name can include numbers,
      lowercase letters, uppercase letters, and hyphens (-). It cannot
      start or end with a hyphen (-).
    Description: Name of S3 bucket for reading genomics operations data
      such as bed files, references, etc.
    Type: String
  EnvironmentValue:
    Description: Environment to deploy. Will be appended as a suffix to select resources. (e.g. prod, prod, prod, test, or individual prod envs, such as nsprod, vyprod, blee prod with prodelopers' initials)
    Type: String
  AlignstatsImageRepo:
    Type: String
    Description: AWS ECR repository name for alignstats docker image
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
  VerifyBamIDImageRepo:
    Type: String
    Description: AWS ECR repository name for verifyBamID docker image
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
  LiftoverIntersectImageRepo:
    Type: String
    Description: AWS ECR repository name for liftover-intersect docker image
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
  LiftoverPreprocessingImageRepo:
    Type: String
    Description: AWS ECR repository name for liftover-preprocessing docker image
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
  LiftoverImageRepo:
    Type: String
    Description: AWS ECR repository name for liftover docker image
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
  StargazerImageRepo:
    Type: String
    Description: AWS ECR repository name for stargazer docker image
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
  IntervarImageRepo:
    Type: String
    Description: AWS ECR repository name for intervar docker image
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
  MpileupImageRepo:
    Type: String
    Description: AWS ECR repository name for mpileup-cassandra docker image
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
  CassandraImageRepo:
    Type: String
    Description: AWS ECR repository name for cassandra docker image
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*
  ConcordanceImageRepo:
    Type: String
    Description: AWS ECR repository name for fingerprint docker image
    AllowedPattern: (?:[a-z0-9]+(?:[:._-][a-z0-9]+)*)*[a-z0-9]+(?:[._-][a-z0-9]+)*


Rules:
  DRAGENSupportedRegionRule:
    Assertions:
    - Assert:
        Fn::Contains:
        - - us-east-1
          - us-west-2
#          - eu-west-1
#          - ap-southeast-2
        - !Ref AWS::Region
      AssertDescription: This Quick Start utilizes a private Dragen AMI which is only available
         in us-east-1 and us-west-2 (N. Virginia and Oregon).  


Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
      Parameters:
        AvailabilityZones:
          Fn::Join:
            - ','
            - !Ref AvailabilityZones
        KeyPairName: !Ref KeyPairName
        NumberOfAZs: '4'
        PrivateSubnet1ACIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2ACIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3ACIDR: !Ref PrivateSubnet3CIDR
        PrivateSubnet4ACIDR: !Ref PrivateSubnet4CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        VPCCIDR: !Ref VPCCIDR
  DragenStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: purpose
          Value: dragen
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/dragen-3.4.12.yaml
      Parameters:
        PrivateSubnet1ID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        PrivateSubnet2ID: !GetAtt VPCStack.Outputs.PrivateSubnet2AID
        PrivateSubnet3ID: !GetAtt VPCStack.Outputs.PrivateSubnet3AID
        PrivateSubnet4ID: !GetAtt VPCStack.Outputs.PrivateSubnet4AID
        VpcId: !GetAtt VPCStack.Outputs.VPCID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        KeyPairName: !Ref KeyPairName
        InstanceType: !Ref DragenInstanceType
        BidPercentage: !Ref BidPercentage
        MinvCpus: !Ref MinvCpus
        DesiredvCpus: !Ref DesiredvCpus
        GenomicsS3Bucket: !Ref GenomicsS3Bucket
        OperationsDataBucket: !Ref OperationsDataBucket
        RetryNumber: !Ref RetryNumber
        DragenTimeout: !Ref DragenTimeout
        EnvironmentValue: !Ref EnvironmentValue
  ReportsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
        - Key: purpose
          Value: reports
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/reports-batch-9.19.parent.yaml
      Parameters: 
        SubnetIds: !Sub "${VPCStack.Outputs.PrivateSubnet1AID}, ${VPCStack.Outputs.PrivateSubnet2AID}, ${VPCStack.Outputs.PrivateSubnet3AID}, ${VPCStack.Outputs.PrivateSubnet4AID}"
        VpcId: !GetAtt VPCStack.Outputs.VPCID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        KeyPairName: !Ref KeyPairName
        InstanceType: !Ref ReportsInstanceType
        PlusInstanceType: !Ref ReportsPlusInstanceType
        IntervarInstanceType: !Ref IntervarInstanceType
        BidPercentage: !Ref BidPercentage
        MinvCpus: !Ref MinvCpus
        DesiredvCpus: !Ref DesiredvCpus
        GenomicsS3Bucket: !Ref GenomicsS3Bucket
        OperationsDataBucket: !Ref OperationsDataBucket
        RetryNumber: !Ref RetryNumber
        EnvironmentValue: !Ref EnvironmentValue
        AlignstatsImageRepo: !Ref AlignstatsImageRepo
        VerifyBamIDImageRepo: !Ref VerifyBamIDImageRepo
        LiftoverIntersectImageRepo: !Ref LiftoverIntersectImageRepo
        LiftoverPreprocessingImageRepo: !Ref LiftoverPreprocessingImageRepo
        LiftoverImageRepo: !Ref LiftoverImageRepo
        StargazerImageRepo: !Ref StargazerImageRepo
        IntervarImageRepo: !Ref IntervarImageRepo
        MpileupImageRepo: !Ref MpileupImageRepo
        CassandraImageRepo: !Ref CassandraImageRepo
        ConcordanceImageRepo: !Ref ConcordanceImageRepo
