AWSTemplateFormatVersion: 2010-09-09

Description: This CloudFormation Template invokes other templates responsible for
  cleaning up AWS Resources (qs-1nlegmi1j)


Parameters:
  QSS3BucketName:
    Description: The Template Bucket Name.
    Type: String
  QSS3KeyPrefix:
    Description: The Template Bucket Prefix.
    Type: String
  Bucket:
    Description: The Bucket which should be emptied.
    Type: String
  Repository:
    Description: The ECR Repository to remove.
    Type: String
  RoleArn:
    Description: The ARN of the Cleanup Role.
    Type: String
  LambdaZipsBucket:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with
      a hyphen (-).
    Description: Bucket name containing lambda zip files
    Type: String


Resources:
  BucketCleanup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/clean-bucket.yaml
      Parameters:
        Bucket: !Ref Bucket
        ServiceToken: !Ref RoleArn
        LambdaZipsBucket: !Ref LambdaZipsBucket
        QSS3KeyPrefix: !Ref QSS3KeyPrefix 
  RepositoryCleanup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/clean-repository.yaml
      Parameters:
        Repository: !Ref Repository
        ServiceToken: !Ref RoleArn
        LambdaZipsBucket: !Ref LambdaZipsBucket
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
