project:
  name: vpc-submodule
  regions:
    - us-east-1
    - us-west-1
    - us-west-2
    - ap-northeast-1
    - ap-northeast-2

tests:
  NVirginia:
    template: templates/aws-vpc.template
    regions:
      - us-east-1
    parameters:
      AvailabilityZones: us-east-1a,us-east-1b,us-east-1c,us-east-1d
      NumberofAZs: '4'
      PrivateSubnet1ACIDR: 10.60.0.0/19
      PrivateSubnet2ACIDR: 10.60.33.0/19
      PrivateSubnet3ACIDR: 10.60.64.0/19
      PrivateSubnet4ACIDR: 10.60.96.0/19
      PublicSubnet1CIDR: 10.60.128.0/20
      PublicSubnet2CIDR: 10.60.145.0/20
      VPCCIDR: 10.60.0.0/16
  NCalifornia:
    template: templates/aws-vpc.template
    regions:
      - us-west-1
    parameters:
      AvailabilityZones: us-west-1a,us-west-1b
      NumberofAZs: '2'
      PrivateSubnet1ACIDR: 10.60.0.0/19
      PrivateSubnet2ACIDR: 10.60.33.0/19
      PublicSubnet1CIDR: 10.60.128.0/20
      PublicSubnet2CIDR: 10.60.145.0/20
      VPCCIDR: 10.60.0.0/16
  Oregon:
    template: templates/aws-vpc.template
    regions:
      - us-west-2
    parameters:
      AvailabilityZones: us-west-2a,us-west-2b,us-west-2c,us-west-2d
      NumberofAZs: '4'
      PrivateSubnet1ACIDR: 10.60.0.0/19
      PrivateSubnet2ACIDR: 10.60.33.0/19
      PrivateSubnet3ACIDR: 10.60.64.0/19
      PrivateSubnet4ACIDR: 10.60.96.0/19
      PublicSubnet1CIDR: 10.60.128.0/20
      PublicSubnet2CIDR: 10.60.145.0/20
      VPCCIDR: 10.60.0.0/16
  Tokyo:
    template: templates/aws-vpc.template
    regions:
      - ap-northeast-1
    parameters:
      AvailabilityZones: ap-northeast-1a,ap-northeast-1c,ap-northeast-1d
      NumberofAZs: '3'
      PrivateSubnet1ACIDR: 10.60.0.0/19
      PrivateSubnet2ACIDR: 10.60.33.0/19
      PrivateSubnet3ACIDR: 10.60.64.0/19
      PublicSubnet1CIDR: 10.60.128.0/20
      PublicSubnet2CIDR: 10.60.145.0/20
      VPCCIDR: 10.60.0.0/16
  Seoul:
    template: templates/aws-vpc.template
    regions:
      - ap-northeast-2
    parameters:
      AvailabilityZones: ap-northeast-2a,ap-northeast-2b,ap-northeast-2c,ap-northeast-2d
      NumberofAZs: '4'
      PrivateSubnet1ACIDR: 10.60.0.0/19
      PrivateSubnet2ACIDR: 10.60.33.0/19
      PrivateSubnet3ACIDR: 10.60.64.0/19
      PublicSubnet1CIDR: 10.60.128.0/20
      PublicSubnet2CIDR: 10.60.145.0/20
      VPCCIDR: 10.60.0.0/16
